# Generated by Django 4.1.7 on 2023-07-12 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryAdress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=256)),
                ("postcode", models.IntegerField()),
                ("street", models.CharField(max_length=256)),
                ("house_number", models.IntegerField()),
                ("apt_number", models.IntegerField()),
                ("phone_number", models.IntegerField()),
                ("delivery_category", models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryPriceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("00", "pickup"),
                            ("01", "city center"),
                            ("02", "clothe to city center"),
                            ("02", "far from city center"),
                            ("04", "town outskirts"),
                            ("05", "suburb"),
                        ],
                        max_length=2,
                    ),
                ),
                ("delivery_price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
                ("description", models.CharField(blank=True, max_length=520)),
                ("size", models.ImageField(blank=True, upload_to="")),
                ("weight", models.ImageField(blank=True, upload_to="")),
                ("price", models.ImageField(blank=True, upload_to="")),
                ("image", models.ImageField(blank=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("order_sum_price", models.IntegerField()),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("CSHD", "cash on delivery"),
                            ("CRDA", "card in advance"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery_adress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pizza_shop.deliveryadress",
                    ),
                ),
                (
                    "delivery_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pizza_shop.deliverypricecategory",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pizza_shop.product",
                    ),
                ),
            ],
        ),
    ]
