# Generated by Django 4.1.7 on 2023-07-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza_shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryadress",
            name="apt_number",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="deliveryadress",
            name="house_number",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="deliveryadress",
            name="phone_number",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="deliveryadress",
            name="postcode",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="deliverypricecategory",
            name="delivery_price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_sum_price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="order", name="quantity", field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
