# Generated by Django 4.1.7 on 2023-07-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza_shop", "0002_alter_deliveryadress_apt_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryadress",
            name="phone_number",
            field=models.CharField(max_length=12),
        ),
    ]
